#cloud-config

hostname: node3.home
manage_etc_hosts: true
apt_preserve_sources_list: true

users:
  - name: cbruner
    primary-group: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: cbruner,video,users,input,docker
    ssh-import-id: None
    lock_passwd: true
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDDUQvKIZGnWnyC+yPsUJI6xqW4ZJjt+t164OOpl3IU/4tXzQWO2zpZSu/kIkLxSDVlIpEHm1QYCxoDtdX0M5xHfHyYAlArJXX0FQtLKRnJJQfvzuh6Ea5ffiADNhZKbrj1nNDclRAatVU0eetsmeIJ3tjTm9YwKAFf9yO5NpuXVluERjBi3gYkQem7decazSEUimgtTNP75FKzW0nKAGa5eTySTha9P/nDgOluSQytkqlFOyPKeGm5Gyy93PGFFWYRW2BloViMOTHE2ubtda31krzOD9m5s58wBCnOciE1YIDJNS7AKf/ZFAseyiAOhSNi2fVe4wKA3QjIXFPsRNaJ colin.d.bruner@gmail.com
