apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: homepage
  labels:
    app: web
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      imagePullSecrets:
        - name: registrykey
      containers:
        - name: web
          image: cbruner/homepage:v1.0.1
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: tls-volume
              mountPath: /etc/nginx/secrets
      volumes:
        - name: tls-volume
          secret:
            secretName: homepage-tls
